Basic implementation of non-playable characters
sloukit/pydew-valley-uzh pull request #27
Opened 2024-07-04 10:19 UTC by michelfinley

A basic implementation of non-playable characters with two randomly wandering NPCs.
The new NPC class in src/sprites.py can be extended later on to achieve the desired behaviour of in- and outgroup members.

2024-07-05 20:39 UTC, michelfinley commented
Added a base implementation for NPC behaviour.
The two NPCs previously wandering around will now try to till, plant and water farmable tiles.
They now also collide with the Player and with other NPCs.

Known bugs:

Sometimes NPCs get stuck inside the Player's hitbox
When NPCs water the plants, the hoe is displayed as the item used instead of the watering can

2024-07-06 12:20 UTC, DhyaneshGhaghada reviewed
well from my perspective the code is clean and abstract moreover, it is just not to crazy and more simple, so i think its ready for process of merging.

2024-07-08 08:31 UTC, Manunz15 requested changes
The features are pretty good, NPCs should handle the hoe when farming but it's a minor problem that can be resolved later on. For now just create a key that unable and disable NPCs since they are still an experimental feature (default should be disable).

2024-07-08 10:33 UTC, Manunz15 approved these changes

2024-07-08 10:35 UTC, merged