Refactor existing event handlers
sloukit/pydew-valley-uzh pull request #61
Opened 2024-07-14 13:55 UTC by michelfinley

## Summary

This PR enhances and fixes the event handling as described in issue #60 .

Every class that handles events should now have a handle_event function, that should be called by the handle_event function of its parent. The root of all event handling is the event_loop function in main.py.

The handle_event function must always return a boolean value indicating whether the event could be handled and should not be handled by any other game element.

## Checklist

- [X] I have tested this change locally and it works as expected.
- [X] I have made sure that the code follows the formatting and style guidelines of the project.

## Labels
`area: code quality`, `game-ui`, `priority: medium`, `type: bugfix`, `type: enhancement`

2024-07-15 14:39 UTC, fortwoone requested changes
This could be merged as-is, but some code readability issues (thankfully pretty minor)

2024-07-15 14:39 UTC, fortwoone commented on src/overlay/soil.py
> +    map: dict[tuple[int, int], Tile]
I'd advise against using this name, as it shadows a built-in iterator (see https://docs.python.org/3/library/functions.html#map).
You could rename it to `tile_map` to differentiate it from said iterator

2024-07-15 16:30 UTC, michelfinley commented on main.py
> +            self.level.player.direction.update((0, 0))
I had problems with being off by a few decimal places when trying to use this in NPC pathfinding, so I got used to use pygame.Vector2 resp. pygame.rect.Rect.update instead.

2024-07-21 12:47 UTC, fortwoone approved these changes
LGTM

2024-07-21 12:47 UTC, fortwoone commented on main.py
> +            # GameState.LEVEL: self.level
What exactly does this achieve?

2024-07-21 12:47 UTC, fortwoone commented on main.py
> +            # GameState.LEVEL: self.level
(Don’t pay attention to this comment, I read further in the code. My bad)

2024-07-21 12:47 UTC, merged